Import('shouse_env')

smart_home_hal_env = shouse_env.Clone()

smart_home_hal_env.AppendUnique(CPPPATH = [
		'#/extlibs/cjson',
	    '#/resource/include',
	    '#/resource/c_common',
        '#/resource/csdk/security/include',
        '#/resource/csdk/include',
        '#/resource/csdk/stack/include',
        '#/resource/c_common/ocrandom/include',
        '#/resource/csdk/logger/include',
        '#/resource/oc_logger/include',
		'#/resource/shouse',
		'#/resource/shouse/spdlog',
		'#/service/simulator/ramlparser/raml',
		'#/service/simulator/ramlparser/raml/model',
		'#/service/simulator/ramlparser/raml/jsonSchemaParser',
		'#/extlibs/yaml/yaml/include',

        '#/resource/shouse/sdk/include',
        '#/resource/shouse/sdk/'
        ])

# IoTivity libs
smart_home_hal_env.AppendUnique(RPATH = [smart_home_hal_env.get('BUILD_DIR')])
smart_home_hal_env.PrependUnique(LIBS = ['coap'])

smart_home_hal_env.AppendUnique(LIBS = ['octbstack'])
smart_home_hal_env.AppendUnique(LIBS = ['oc'])

smart_home_hal_env.AppendUnique(LIBS = ['ocsrm'])

smart_home_hal_env.AppendUnique(LIBS = ['RamlParser'])

smart_home_hal_env.AppendUnique(LIBS = ['shouse_core'])
smart_home_hal_env.AppendUnique(LIBS = ['shouse_utils'])

smart_home_hal_env.AppendUnique(CXXFLAGS = ['-g'])

# Light HAL

light_hal = smart_home_hal_env.SharedLibrary('light_hal', ['light_hal.cpp'])
smart_home_hal_env.InstallTarget(light_hal, 'liblight_hal')
smart_home_hal_env.UserInstallTargetLib(light_hal, 'liblight_hal')

smart_home_hal_env.AppendTarget('HAL')

# Camera HAL (clone environment to prevent linking of other HALs with OpenCV)

smart_home_camera_hal_env = smart_home_hal_env.Clone()

# OpenCV libs
smart_home_camera_hal_env.AppendUnique(LIBS = ['opencv_imgproc'])
smart_home_camera_hal_env.AppendUnique(LIBS = ['opencv_core'])
smart_home_camera_hal_env.AppendUnique(LIBS = ['opencv_videoio']) 
smart_home_camera_hal_env.AppendUnique(LIBS = ['opencv_highgui']) 
smart_home_camera_hal_env.AppendUnique(LIBS = ['opencv_imgcodecs'])

camera_hal = smart_home_camera_hal_env.SharedLibrary('camera_hal', ['camera_hal.cpp'])
smart_home_camera_hal_env.InstallTarget(camera_hal, 'libcamera_hal')
smart_home_camera_hal_env.UserInstallTargetLib(camera_hal, 'libcamera_hal')

smart_home_camera_hal_env.AppendTarget('CameraHAL')
