Import('shouse_env')

SConscript('#resource/shouse/apps/raml_test/SConscript')
SConscript('#resource/shouse/apps/hal_test/SConscript')

SConscript('#resource/shouse/apps/smart_home/SConscript')

# Legacy apps
SConscript('#resource/shouse/apps/legacy/SConscript')

# RP2 HAL DLLS
SConscript('#resource/shouse/apps/rp2/HAL/numpad_hal/SConscript')
SConscript('#resource/shouse/apps/rp2/HAL/diod_hal/SConscript')
SConscript('#resource/shouse/apps/rp2/HAL/motion_hal/SConscript')
SConscript('#resource/shouse/apps/rp2/HAL/temperature_ds18b20/SConscript')
SConscript('#resource/shouse/apps/rp2/HAL/pressure_bmp180/SConscript')
SConscript('#resource/shouse/apps/rp2/HAL/rfid_hal/SConscript')

