Import('shouse_env')

hal_test_env = shouse_env.Clone()

hal_test_env.AppendUnique(CPPPATH = [
		'#/extlibs/cjson',
	    '#/resource/include',
	    '#/resource/c_common',
        '#/resource/csdk/security/include',
        '#/resource/csdk/include',
        '#/resource/csdk/stack/include',
        '#/resource/c_common/ocrandom/include',
        '#/resource/csdk/logger/include',
        '#/resource/oc_logger/include',
		'#/resource/shouse',
		'#/resource/shouse/spdlog',
#		'#/service/simulator/ramlparser/raml',
#		'#/service/simulator/ramlparser/raml/model',
#		'#/service/simulator/ramlparser/raml/jsonSchemaParser',
#		'#/extlibs/yaml/yaml/include',

        '#/resource/shouse/sdk/include',
        '#/resource/shouse/sdk/'
        ])

# IoTivity libs
hal_test_env.AppendUnique(RPATH = [hal_test_env.get('BUILD_DIR')])
hal_test_env.PrependUnique(LIBS = ['coap'])

hal_test_env.AppendUnique(LIBS = ['octbstack'])
hal_test_env.AppendUnique(LIBS = ['oc'])

hal_test_env.AppendUnique(LIBS = ['ocsrm'])

#hal_test_env.AppendUnique(LIBS = ['RamlParser'])

hal_test_env.AppendUnique(LIBS = ['shouse_core'])
hal_test_env.AppendUnique(LIBS = ['shouse_utils'])

hal_test_env.AppendUnique(CXXFLAGS = ['-g'])

# OpenCV libs
#hal_test_env.AppendUnique(LIBS = ['opencv_imgproc'])
#hal_test_env.AppendUnique(LIBS = ['opencv_core'])
#hal_test_env.AppendUnique(LIBS = ['opencv_videoio']) 
#hal_test_env.AppendUnique(LIBS = ['opencv_highgui']) 
#hal_test_env.AppendUnique(LIBS = ['opencv_imgcodecs'])

# HAL-based interface
#hal_test_env.Program('HAL_test_server', ['test_server.cpp'])
#hal_test_env.Program('HAL_test_client', ['test_client.cpp'])

# DLL Light HAL module
hal_test_env.SharedLibrary('HAL_light', ['test_dll_hal.cpp'])

# DLL Videocamera HAL module
#hal_test_env.SharedLibrary('HAL_videocamera', ['camera_dll_hal.cpp'])

hal_test_env.AppendTarget('hal_test')
