Import('env')

##
# Examples build script
##
lib_env = env.Clone()
SConscript('#build_common/thread.scons', exports = {'thread_env' : lib_env})

# Add third party libraries
SConscript('#resource/third_party_libs.scons', 'lib_env')
shouse_env = lib_env.Clone()

target_os = shouse_env.get('TARGET_OS')

shouse_env.AppendUnique(CPPPATH = [
		'#/extlibs/cjson',
	    '#/resource/include',
	    '#/resource/c_common',
        '#/resource/csdk/security/include',
        '#/resource/csdk/include',
        '#/resource/csdk/stack/include',
        '#/resource/c_common/ocrandom/include',
        '#/resource/csdk/logger/include',
        '#/resource/oc_logger/include',
		'#/resource/shouse',
		'#/resource/shouse/spdlog',
		'#/service/simulator/ramlparser/raml',
		'#/service/simulator/ramlparser/raml/model',
		'#/service/simulator/ramlparser/raml/jsonSchemaParser',
		'#/extlibs/yaml/yaml/include'
        ])

# OpenCV libs
shouse_env.AppendUnique(LIBS = ['opencv_imgproc'])
shouse_env.AppendUnique(LIBS = ['opencv_core'])
shouse_env.AppendUnique(LIBS = ['opencv_videoio']) 
shouse_env.AppendUnique(LIBS = ['opencv_highgui']) 
shouse_env.AppendUnique(LIBS = ['opencv_imgcodecs']) 

# IoTivity libs
shouse_env.AppendUnique(RPATH = [shouse_env.get('BUILD_DIR')])
shouse_env.PrependUnique(LIBS = ['coap'])

shouse_env.AppendUnique(LIBS = ['octbstack'])
shouse_env.AppendUnique(LIBS = ['oc'])

shouse_env.AppendUnique(LIBS = ['ocsrm'])

shouse_env.AppendUnique(LIBS = ['RamlParser'])

compiler = shouse_env.get('CXX')
if 'g++' in compiler:
    shouse_env.AppendUnique(CXXFLAGS = ['-std=c++11'])

if target_os in ['msys_nt', 'windows']:
    shouse_env.PrependUnique(LIBS = ['mswsock', 'ws2_32', 'iphlpapi', 'ole32'])
else:
    shouse_env.PrependUnique(LIBS = ['oc_logger'])

if shouse_env.get('SECURED') == '1':
    shouse_env.AppendUnique(LIBS = ['mbedtls', 'mbedx509','mbedcrypto'])
    if target_os in ['msys_nt', 'windows']:
        shouse_env.AppendUnique(LIBS = ['advapi32'])

if target_os == 'android':
    shouse_env.AppendUnique(CXXFLAGS = ['-frtti', '-fexceptions'])
    shouse_env.AppendUnique(LIBS = ['gnustl_shared'])

    if not shouse_env.get('RELEASE'):
        shouse_env.AppendUnique(LIBS = ['log'])

if target_os in ['msys_nt', 'windows']:
    shouse_env.AppendUnique(LIBS = ['Comctl32', 'Gdi32', 'User32'])

my_smpserver = shouse_env.Program('my_simpleserver', ['my_simpleserver.cpp', 'binarylightserver.cpp'])

my_smpclient = shouse_env.Program('my_simpleclient', ['my_simpleclient.cpp', 'binarylightclient.cpp'])

shouse_env.Program('raml_test', ['raml_test.cpp'])

shouse_env.Program('videocameraserver', ['videocameraserverprocess.cpp', 'videocameraserver.cpp'])
shouse_env.Program('videocameraclient', ['videocameraclientprocess.cpp', 'videocameraclient.cpp'])

Alias("shouse", [my_smpclient, my_smpserver])
shouse_env.AppendTarget('shouse')
