Import('shouse_env')

SConscript('#resource/shouse/apps/raml_test/SConscript')
SConscript('#resource/shouse/apps/hal_test/SConscript')

SConscript('#resource/shouse/apps/smart_home/SConscript')

# Legacy apps
SConscript('#resource/shouse/apps/legacy/SConscript')

# RP2 bcm lib
SConscript('#resource/shouse/apps/rp2/bcm2835/SConscript')
# RP2 HAL DLLS
SConscript('#resource/shouse/apps/rp2/HAL/SConscript')

# RP2 test
SConscript('#resource/shouse/apps/rp2/test/SConsript')

# test1
SConscript('#resource/shouse/apps/test1/SConscript')
